-- =============================================================================
-- Phase 3 — RBAC Setup
-- =============================================================================
-- Project  : PriorAuthIQ Healthcare Data Platform
-- Phase    : 3 of 16
-- Dependency: Phase 2 complete (warehouses exist)
-- Scope    : Roles, hierarchy, object-level grants, user assignment scaffolds
-- Owner    : SECURITYADMIN (role creation and grants)
-- =============================================================================
--
-- Roles (7 custom roles):
--   PA_DATA_ENGINEER_ROLE  — Pipeline dev: ingestion, transformation, task mgmt
--   PA_ANALYST_ROLE        — Read-only business consumption on ANALYTICS
--   PA_AI_ENGINEER_ROLE    — Cortex AI: AI pipelines, semantic views, agents
--   PA_DATA_STEWARD_ROLE   — Governance: tagging, classification, masking
--   PA_AUDIT_ROLE          — Read-only on audit DB (grants deferred to Phase 11)
--   PA_PHI_ACCESS_ROLE     — Unmasked PHI: break-glass, isolated
--   PA_CICD_ROLE           — GitHub Actions: deploys across environments
--
-- Hierarchy:
--   SYSADMIN
--     ├── PA_CICD_ROLE
--     ├── PA_DATA_ENGINEER_ROLE
--     │       └── PA_ANALYST_ROLE
--     ├── PA_AI_ENGINEER_ROLE
--     │       └── PA_ANALYST_ROLE
--     ├── PA_PHI_ACCESS_ROLE  (isolated)
--     └── PA_AUDIT_ROLE
--   SECURITYADMIN
--     └── PA_DATA_STEWARD_ROLE
--
-- Phase boundary — the following are NOT done here:
--   - Resource monitors             (Phase 4)
--   - Masking policy assignment     (Phase 9)
--   - Audit DB grants               (Phase 11)
-- =============================================================================


-- =============================================================================
-- SECTION 1: Role Creation
-- =============================================================================
-- Roles are created under SECURITYADMIN per the role architecture.
-- SECURITYADMIN manages the role hierarchy; it does not own data objects.
-- =============================================================================

USE ROLE SECURITYADMIN;

CREATE ROLE IF NOT EXISTS PA_DATA_ENGINEER_ROLE
  COMMENT = 'Pipeline development — ingestion, transformation, task management';

CREATE ROLE IF NOT EXISTS PA_ANALYST_ROLE
  COMMENT = 'Read-only business consumption on ANALYTICS schema';

CREATE ROLE IF NOT EXISTS PA_AI_ENGINEER_ROLE
  COMMENT = 'Cortex AI — builds AI pipelines, semantic views, agent specs';

CREATE ROLE IF NOT EXISTS PA_DATA_STEWARD_ROLE
  COMMENT = 'Governance — classification, tagging, masking policy management';

CREATE ROLE IF NOT EXISTS PA_AUDIT_ROLE
  COMMENT = 'Read-only access to audit DB — grants deferred to Phase 11';

CREATE ROLE IF NOT EXISTS PA_PHI_ACCESS_ROLE
  COMMENT = 'Unmasked PHI access — break-glass tier, tightly controlled, isolated';

CREATE ROLE IF NOT EXISTS PA_CICD_ROLE
  COMMENT = 'GitHub Actions service account — deploys objects across DEV/QA/PROD';


-- =============================================================================
-- SECTION 2: Role Hierarchy
-- =============================================================================
-- PA_ANALYST_ROLE inherits up into both PA_DATA_ENGINEER_ROLE and
-- PA_AI_ENGINEER_ROLE, so both can read Gold-layer analytics.
--
-- PA_PHI_ACCESS_ROLE is isolated — it does not inherit into any role
-- and no role inherits it (except SYSADMIN for administrative access).
-- =============================================================================

USE ROLE SECURITYADMIN;

-- Analyst inherits into Data Engineer and AI Engineer
GRANT ROLE PA_ANALYST_ROLE TO ROLE PA_DATA_ENGINEER_ROLE;
GRANT ROLE PA_ANALYST_ROLE TO ROLE PA_AI_ENGINEER_ROLE;

-- All functional roles inherit into SYSADMIN
GRANT ROLE PA_DATA_ENGINEER_ROLE TO ROLE SYSADMIN;
GRANT ROLE PA_AI_ENGINEER_ROLE   TO ROLE SYSADMIN;
GRANT ROLE PA_CICD_ROLE          TO ROLE SYSADMIN;
GRANT ROLE PA_AUDIT_ROLE         TO ROLE SYSADMIN;
GRANT ROLE PA_PHI_ACCESS_ROLE    TO ROLE SYSADMIN;

-- Data Steward reports to SECURITYADMIN (governance chain)
GRANT ROLE PA_DATA_STEWARD_ROLE TO ROLE SECURITYADMIN;


-- =============================================================================
-- SECTION 3: Warehouse USAGE Grants
-- =============================================================================
-- USAGE only — never ownership. Each role gets the warehouse(s) it needs.
-- =============================================================================

USE ROLE SECURITYADMIN;

-- Data Engineer: ingestion + transformation compute
GRANT USAGE ON WAREHOUSE PA_INGESTION_WH TO ROLE PA_DATA_ENGINEER_ROLE;
GRANT USAGE ON WAREHOUSE PA_TRANSFORM_WH TO ROLE PA_DATA_ENGINEER_ROLE;

-- Analyst: query/BI compute
GRANT USAGE ON WAREHOUSE PA_QUERY_WH TO ROLE PA_ANALYST_ROLE;

-- AI Engineer: Cortex AI compute
GRANT USAGE ON WAREHOUSE PA_AI_CORTEX_WH TO ROLE PA_AI_ENGINEER_ROLE;

-- Data Steward: admin compute for governance tasks
GRANT USAGE ON WAREHOUSE PA_ADMIN_WH TO ROLE PA_DATA_STEWARD_ROLE;

-- CI/CD: dedicated deployment compute
GRANT USAGE ON WAREHOUSE PA_CICD_WH TO ROLE PA_CICD_ROLE;

-- PHI Access: query compute for break-glass data access
GRANT USAGE ON WAREHOUSE PA_QUERY_WH TO ROLE PA_PHI_ACCESS_ROLE;

-- Audit: query compute for audit log review
GRANT USAGE ON WAREHOUSE PA_QUERY_WH TO ROLE PA_AUDIT_ROLE;


-- =============================================================================
-- SECTION 4: Database & Schema USAGE Grants
-- =============================================================================
-- Applied identically across all three environment databases.
-- Grants follow least-privilege: each role gets only the schemas it needs.
-- =============================================================================

USE ROLE SECURITYADMIN;

-- -------------------------------------------------------------------------
-- 4a. PA_DEV_DB
-- -------------------------------------------------------------------------

GRANT USAGE ON DATABASE PA_DEV_DB TO ROLE PA_DATA_ENGINEER_ROLE;
GRANT USAGE ON SCHEMA PA_DEV_DB.RAW       TO ROLE PA_DATA_ENGINEER_ROLE;
GRANT USAGE ON SCHEMA PA_DEV_DB.CURATED   TO ROLE PA_DATA_ENGINEER_ROLE;
GRANT USAGE ON SCHEMA PA_DEV_DB.ANALYTICS TO ROLE PA_DATA_ENGINEER_ROLE;
GRANT USAGE ON SCHEMA PA_DEV_DB.AI        TO ROLE PA_DATA_ENGINEER_ROLE;

GRANT USAGE ON DATABASE PA_DEV_DB TO ROLE PA_ANALYST_ROLE;
GRANT USAGE ON SCHEMA PA_DEV_DB.ANALYTICS TO ROLE PA_ANALYST_ROLE;

GRANT USAGE ON DATABASE PA_DEV_DB TO ROLE PA_AI_ENGINEER_ROLE;
GRANT USAGE ON SCHEMA PA_DEV_DB.AI        TO ROLE PA_AI_ENGINEER_ROLE;
GRANT USAGE ON SCHEMA PA_DEV_DB.ANALYTICS TO ROLE PA_AI_ENGINEER_ROLE;

GRANT USAGE ON DATABASE PA_DEV_DB TO ROLE PA_DATA_STEWARD_ROLE;
GRANT USAGE ON SCHEMA PA_DEV_DB.RAW       TO ROLE PA_DATA_STEWARD_ROLE;
GRANT USAGE ON SCHEMA PA_DEV_DB.CURATED   TO ROLE PA_DATA_STEWARD_ROLE;
GRANT USAGE ON SCHEMA PA_DEV_DB.ANALYTICS TO ROLE PA_DATA_STEWARD_ROLE;
GRANT USAGE ON SCHEMA PA_DEV_DB.AI        TO ROLE PA_DATA_STEWARD_ROLE;

GRANT USAGE ON DATABASE PA_DEV_DB TO ROLE PA_CICD_ROLE;
GRANT USAGE ON SCHEMA PA_DEV_DB.RAW       TO ROLE PA_CICD_ROLE;
GRANT USAGE ON SCHEMA PA_DEV_DB.CURATED   TO ROLE PA_CICD_ROLE;
GRANT USAGE ON SCHEMA PA_DEV_DB.ANALYTICS TO ROLE PA_CICD_ROLE;
GRANT USAGE ON SCHEMA PA_DEV_DB.AI        TO ROLE PA_CICD_ROLE;

GRANT USAGE ON DATABASE PA_DEV_DB TO ROLE PA_PHI_ACCESS_ROLE;
GRANT USAGE ON SCHEMA PA_DEV_DB.ANALYTICS TO ROLE PA_PHI_ACCESS_ROLE;
GRANT USAGE ON SCHEMA PA_DEV_DB.AI        TO ROLE PA_PHI_ACCESS_ROLE;

-- -------------------------------------------------------------------------
-- 4b. PA_QA_DB
-- -------------------------------------------------------------------------

GRANT USAGE ON DATABASE PA_QA_DB TO ROLE PA_DATA_ENGINEER_ROLE;
GRANT USAGE ON SCHEMA PA_QA_DB.RAW       TO ROLE PA_DATA_ENGINEER_ROLE;
GRANT USAGE ON SCHEMA PA_QA_DB.CURATED   TO ROLE PA_DATA_ENGINEER_ROLE;
GRANT USAGE ON SCHEMA PA_QA_DB.ANALYTICS TO ROLE PA_DATA_ENGINEER_ROLE;
GRANT USAGE ON SCHEMA PA_QA_DB.AI        TO ROLE PA_DATA_ENGINEER_ROLE;

GRANT USAGE ON DATABASE PA_QA_DB TO ROLE PA_ANALYST_ROLE;
GRANT USAGE ON SCHEMA PA_QA_DB.ANALYTICS TO ROLE PA_ANALYST_ROLE;

GRANT USAGE ON DATABASE PA_QA_DB TO ROLE PA_AI_ENGINEER_ROLE;
GRANT USAGE ON SCHEMA PA_QA_DB.AI        TO ROLE PA_AI_ENGINEER_ROLE;
GRANT USAGE ON SCHEMA PA_QA_DB.ANALYTICS TO ROLE PA_AI_ENGINEER_ROLE;

GRANT USAGE ON DATABASE PA_QA_DB TO ROLE PA_DATA_STEWARD_ROLE;
GRANT USAGE ON SCHEMA PA_QA_DB.RAW       TO ROLE PA_DATA_STEWARD_ROLE;
GRANT USAGE ON SCHEMA PA_QA_DB.CURATED   TO ROLE PA_DATA_STEWARD_ROLE;
GRANT USAGE ON SCHEMA PA_QA_DB.ANALYTICS TO ROLE PA_DATA_STEWARD_ROLE;
GRANT USAGE ON SCHEMA PA_QA_DB.AI        TO ROLE PA_DATA_STEWARD_ROLE;

GRANT USAGE ON DATABASE PA_QA_DB TO ROLE PA_CICD_ROLE;
GRANT USAGE ON SCHEMA PA_QA_DB.RAW       TO ROLE PA_CICD_ROLE;
GRANT USAGE ON SCHEMA PA_QA_DB.CURATED   TO ROLE PA_CICD_ROLE;
GRANT USAGE ON SCHEMA PA_QA_DB.ANALYTICS TO ROLE PA_CICD_ROLE;
GRANT USAGE ON SCHEMA PA_QA_DB.AI        TO ROLE PA_CICD_ROLE;

GRANT USAGE ON DATABASE PA_QA_DB TO ROLE PA_PHI_ACCESS_ROLE;
GRANT USAGE ON SCHEMA PA_QA_DB.ANALYTICS TO ROLE PA_PHI_ACCESS_ROLE;
GRANT USAGE ON SCHEMA PA_QA_DB.AI        TO ROLE PA_PHI_ACCESS_ROLE;

-- -------------------------------------------------------------------------
-- 4c. PA_PROD_DB
-- -------------------------------------------------------------------------

GRANT USAGE ON DATABASE PA_PROD_DB TO ROLE PA_DATA_ENGINEER_ROLE;
GRANT USAGE ON SCHEMA PA_PROD_DB.RAW       TO ROLE PA_DATA_ENGINEER_ROLE;
GRANT USAGE ON SCHEMA PA_PROD_DB.CURATED   TO ROLE PA_DATA_ENGINEER_ROLE;
GRANT USAGE ON SCHEMA PA_PROD_DB.ANALYTICS TO ROLE PA_DATA_ENGINEER_ROLE;
GRANT USAGE ON SCHEMA PA_PROD_DB.AI        TO ROLE PA_DATA_ENGINEER_ROLE;

GRANT USAGE ON DATABASE PA_PROD_DB TO ROLE PA_ANALYST_ROLE;
GRANT USAGE ON SCHEMA PA_PROD_DB.ANALYTICS TO ROLE PA_ANALYST_ROLE;

GRANT USAGE ON DATABASE PA_PROD_DB TO ROLE PA_AI_ENGINEER_ROLE;
GRANT USAGE ON SCHEMA PA_PROD_DB.AI        TO ROLE PA_AI_ENGINEER_ROLE;
GRANT USAGE ON SCHEMA PA_PROD_DB.ANALYTICS TO ROLE PA_AI_ENGINEER_ROLE;

GRANT USAGE ON DATABASE PA_PROD_DB TO ROLE PA_DATA_STEWARD_ROLE;
GRANT USAGE ON SCHEMA PA_PROD_DB.RAW       TO ROLE PA_DATA_STEWARD_ROLE;
GRANT USAGE ON SCHEMA PA_PROD_DB.CURATED   TO ROLE PA_DATA_STEWARD_ROLE;
GRANT USAGE ON SCHEMA PA_PROD_DB.ANALYTICS TO ROLE PA_DATA_STEWARD_ROLE;
GRANT USAGE ON SCHEMA PA_PROD_DB.AI        TO ROLE PA_DATA_STEWARD_ROLE;

GRANT USAGE ON DATABASE PA_PROD_DB TO ROLE PA_CICD_ROLE;
GRANT USAGE ON SCHEMA PA_PROD_DB.RAW       TO ROLE PA_CICD_ROLE;
GRANT USAGE ON SCHEMA PA_PROD_DB.CURATED   TO ROLE PA_CICD_ROLE;
GRANT USAGE ON SCHEMA PA_PROD_DB.ANALYTICS TO ROLE PA_CICD_ROLE;
GRANT USAGE ON SCHEMA PA_PROD_DB.AI        TO ROLE PA_CICD_ROLE;

GRANT USAGE ON DATABASE PA_PROD_DB TO ROLE PA_PHI_ACCESS_ROLE;
GRANT USAGE ON SCHEMA PA_PROD_DB.ANALYTICS TO ROLE PA_PHI_ACCESS_ROLE;
GRANT USAGE ON SCHEMA PA_PROD_DB.AI        TO ROLE PA_PHI_ACCESS_ROLE;


-- =============================================================================
-- SECTION 5: Object-Level Operational Grants
-- =============================================================================
-- Grants on existing and future objects per schema per environment.
-- Ownership stays with SYSADMIN — these are operational grants only.
-- =============================================================================

USE ROLE SECURITYADMIN;

-- =========================================================================
-- 5a. PA_DATA_ENGINEER_ROLE — Pipeline Development Grants
-- =========================================================================
-- RAW: create ingestion objects (tables, stages, file formats, pipes, streams, tasks)
-- CURATED: create transformation objects (dynamic tables, views)
-- ANALYTICS: read access (inherited from analyst, explicit future grants here)
-- AI: create data products for AI use cases
-- =========================================================================

-- --- PA_DEV_DB ---

-- RAW schema: ingestion object creation
GRANT CREATE TABLE       ON SCHEMA PA_DEV_DB.RAW TO ROLE PA_DATA_ENGINEER_ROLE;
GRANT CREATE STAGE       ON SCHEMA PA_DEV_DB.RAW TO ROLE PA_DATA_ENGINEER_ROLE;
GRANT CREATE FILE FORMAT ON SCHEMA PA_DEV_DB.RAW TO ROLE PA_DATA_ENGINEER_ROLE;
GRANT CREATE PIPE        ON SCHEMA PA_DEV_DB.RAW TO ROLE PA_DATA_ENGINEER_ROLE;
GRANT CREATE STREAM      ON SCHEMA PA_DEV_DB.RAW TO ROLE PA_DATA_ENGINEER_ROLE;
GRANT CREATE TASK        ON SCHEMA PA_DEV_DB.RAW TO ROLE PA_DATA_ENGINEER_ROLE;

-- CURATED schema: transformation object creation
GRANT CREATE DYNAMIC TABLE ON SCHEMA PA_DEV_DB.CURATED TO ROLE PA_DATA_ENGINEER_ROLE;
GRANT CREATE VIEW           ON SCHEMA PA_DEV_DB.CURATED TO ROLE PA_DATA_ENGINEER_ROLE;

-- AI schema: data product creation for AI use cases
GRANT CREATE TABLE        ON SCHEMA PA_DEV_DB.AI TO ROLE PA_DATA_ENGINEER_ROLE;
GRANT CREATE VIEW         ON SCHEMA PA_DEV_DB.AI TO ROLE PA_DATA_ENGINEER_ROLE;
GRANT CREATE DYNAMIC TABLE ON SCHEMA PA_DEV_DB.AI TO ROLE PA_DATA_ENGINEER_ROLE;

-- SELECT on existing + future objects across operational schemas
GRANT SELECT ON ALL TABLES    IN SCHEMA PA_DEV_DB.RAW       TO ROLE PA_DATA_ENGINEER_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PA_DEV_DB.RAW       TO ROLE PA_DATA_ENGINEER_ROLE;
GRANT SELECT ON ALL TABLES    IN SCHEMA PA_DEV_DB.CURATED   TO ROLE PA_DATA_ENGINEER_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PA_DEV_DB.CURATED   TO ROLE PA_DATA_ENGINEER_ROLE;
GRANT SELECT ON ALL VIEWS     IN SCHEMA PA_DEV_DB.CURATED   TO ROLE PA_DATA_ENGINEER_ROLE;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA PA_DEV_DB.CURATED   TO ROLE PA_DATA_ENGINEER_ROLE;
GRANT SELECT ON ALL TABLES    IN SCHEMA PA_DEV_DB.ANALYTICS TO ROLE PA_DATA_ENGINEER_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PA_DEV_DB.ANALYTICS TO ROLE PA_DATA_ENGINEER_ROLE;
GRANT SELECT ON ALL VIEWS     IN SCHEMA PA_DEV_DB.ANALYTICS TO ROLE PA_DATA_ENGINEER_ROLE;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA PA_DEV_DB.ANALYTICS TO ROLE PA_DATA_ENGINEER_ROLE;
GRANT SELECT ON ALL TABLES    IN SCHEMA PA_DEV_DB.AI        TO ROLE PA_DATA_ENGINEER_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PA_DEV_DB.AI        TO ROLE PA_DATA_ENGINEER_ROLE;
GRANT SELECT ON ALL VIEWS     IN SCHEMA PA_DEV_DB.AI        TO ROLE PA_DATA_ENGINEER_ROLE;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA PA_DEV_DB.AI        TO ROLE PA_DATA_ENGINEER_ROLE;

-- --- PA_QA_DB ---

GRANT CREATE TABLE       ON SCHEMA PA_QA_DB.RAW TO ROLE PA_DATA_ENGINEER_ROLE;
GRANT CREATE STAGE       ON SCHEMA PA_QA_DB.RAW TO ROLE PA_DATA_ENGINEER_ROLE;
GRANT CREATE FILE FORMAT ON SCHEMA PA_QA_DB.RAW TO ROLE PA_DATA_ENGINEER_ROLE;
GRANT CREATE PIPE        ON SCHEMA PA_QA_DB.RAW TO ROLE PA_DATA_ENGINEER_ROLE;
GRANT CREATE STREAM      ON SCHEMA PA_QA_DB.RAW TO ROLE PA_DATA_ENGINEER_ROLE;
GRANT CREATE TASK        ON SCHEMA PA_QA_DB.RAW TO ROLE PA_DATA_ENGINEER_ROLE;

GRANT CREATE DYNAMIC TABLE ON SCHEMA PA_QA_DB.CURATED TO ROLE PA_DATA_ENGINEER_ROLE;
GRANT CREATE VIEW           ON SCHEMA PA_QA_DB.CURATED TO ROLE PA_DATA_ENGINEER_ROLE;

GRANT CREATE TABLE        ON SCHEMA PA_QA_DB.AI TO ROLE PA_DATA_ENGINEER_ROLE;
GRANT CREATE VIEW         ON SCHEMA PA_QA_DB.AI TO ROLE PA_DATA_ENGINEER_ROLE;
GRANT CREATE DYNAMIC TABLE ON SCHEMA PA_QA_DB.AI TO ROLE PA_DATA_ENGINEER_ROLE;

GRANT SELECT ON ALL TABLES    IN SCHEMA PA_QA_DB.RAW       TO ROLE PA_DATA_ENGINEER_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PA_QA_DB.RAW       TO ROLE PA_DATA_ENGINEER_ROLE;
GRANT SELECT ON ALL TABLES    IN SCHEMA PA_QA_DB.CURATED   TO ROLE PA_DATA_ENGINEER_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PA_QA_DB.CURATED   TO ROLE PA_DATA_ENGINEER_ROLE;
GRANT SELECT ON ALL VIEWS     IN SCHEMA PA_QA_DB.CURATED   TO ROLE PA_DATA_ENGINEER_ROLE;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA PA_QA_DB.CURATED   TO ROLE PA_DATA_ENGINEER_ROLE;
GRANT SELECT ON ALL TABLES    IN SCHEMA PA_QA_DB.ANALYTICS TO ROLE PA_DATA_ENGINEER_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PA_QA_DB.ANALYTICS TO ROLE PA_DATA_ENGINEER_ROLE;
GRANT SELECT ON ALL VIEWS     IN SCHEMA PA_QA_DB.ANALYTICS TO ROLE PA_DATA_ENGINEER_ROLE;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA PA_QA_DB.ANALYTICS TO ROLE PA_DATA_ENGINEER_ROLE;
GRANT SELECT ON ALL TABLES    IN SCHEMA PA_QA_DB.AI        TO ROLE PA_DATA_ENGINEER_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PA_QA_DB.AI        TO ROLE PA_DATA_ENGINEER_ROLE;
GRANT SELECT ON ALL VIEWS     IN SCHEMA PA_QA_DB.AI        TO ROLE PA_DATA_ENGINEER_ROLE;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA PA_QA_DB.AI        TO ROLE PA_DATA_ENGINEER_ROLE;

-- --- PA_PROD_DB ---

GRANT CREATE TABLE       ON SCHEMA PA_PROD_DB.RAW TO ROLE PA_DATA_ENGINEER_ROLE;
GRANT CREATE STAGE       ON SCHEMA PA_PROD_DB.RAW TO ROLE PA_DATA_ENGINEER_ROLE;
GRANT CREATE FILE FORMAT ON SCHEMA PA_PROD_DB.RAW TO ROLE PA_DATA_ENGINEER_ROLE;
GRANT CREATE PIPE        ON SCHEMA PA_PROD_DB.RAW TO ROLE PA_DATA_ENGINEER_ROLE;
GRANT CREATE STREAM      ON SCHEMA PA_PROD_DB.RAW TO ROLE PA_DATA_ENGINEER_ROLE;
GRANT CREATE TASK        ON SCHEMA PA_PROD_DB.RAW TO ROLE PA_DATA_ENGINEER_ROLE;

GRANT CREATE DYNAMIC TABLE ON SCHEMA PA_PROD_DB.CURATED TO ROLE PA_DATA_ENGINEER_ROLE;
GRANT CREATE VIEW           ON SCHEMA PA_PROD_DB.CURATED TO ROLE PA_DATA_ENGINEER_ROLE;

GRANT CREATE TABLE        ON SCHEMA PA_PROD_DB.AI TO ROLE PA_DATA_ENGINEER_ROLE;
GRANT CREATE VIEW         ON SCHEMA PA_PROD_DB.AI TO ROLE PA_DATA_ENGINEER_ROLE;
GRANT CREATE DYNAMIC TABLE ON SCHEMA PA_PROD_DB.AI TO ROLE PA_DATA_ENGINEER_ROLE;

GRANT SELECT ON ALL TABLES    IN SCHEMA PA_PROD_DB.RAW       TO ROLE PA_DATA_ENGINEER_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PA_PROD_DB.RAW       TO ROLE PA_DATA_ENGINEER_ROLE;
GRANT SELECT ON ALL TABLES    IN SCHEMA PA_PROD_DB.CURATED   TO ROLE PA_DATA_ENGINEER_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PA_PROD_DB.CURATED   TO ROLE PA_DATA_ENGINEER_ROLE;
GRANT SELECT ON ALL VIEWS     IN SCHEMA PA_PROD_DB.CURATED   TO ROLE PA_DATA_ENGINEER_ROLE;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA PA_PROD_DB.CURATED   TO ROLE PA_DATA_ENGINEER_ROLE;
GRANT SELECT ON ALL TABLES    IN SCHEMA PA_PROD_DB.ANALYTICS TO ROLE PA_DATA_ENGINEER_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PA_PROD_DB.ANALYTICS TO ROLE PA_DATA_ENGINEER_ROLE;
GRANT SELECT ON ALL VIEWS     IN SCHEMA PA_PROD_DB.ANALYTICS TO ROLE PA_DATA_ENGINEER_ROLE;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA PA_PROD_DB.ANALYTICS TO ROLE PA_DATA_ENGINEER_ROLE;
GRANT SELECT ON ALL TABLES    IN SCHEMA PA_PROD_DB.AI        TO ROLE PA_DATA_ENGINEER_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PA_PROD_DB.AI        TO ROLE PA_DATA_ENGINEER_ROLE;
GRANT SELECT ON ALL VIEWS     IN SCHEMA PA_PROD_DB.AI        TO ROLE PA_DATA_ENGINEER_ROLE;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA PA_PROD_DB.AI        TO ROLE PA_DATA_ENGINEER_ROLE;


-- =========================================================================
-- 5b. PA_ANALYST_ROLE — Read-Only Consumption Grants
-- =========================================================================
-- ANALYTICS: SELECT on all current and future tables + views
-- No CREATE privileges — analysts consume only
-- =========================================================================

-- --- PA_DEV_DB ---
GRANT SELECT ON ALL TABLES    IN SCHEMA PA_DEV_DB.ANALYTICS TO ROLE PA_ANALYST_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PA_DEV_DB.ANALYTICS TO ROLE PA_ANALYST_ROLE;
GRANT SELECT ON ALL VIEWS     IN SCHEMA PA_DEV_DB.ANALYTICS TO ROLE PA_ANALYST_ROLE;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA PA_DEV_DB.ANALYTICS TO ROLE PA_ANALYST_ROLE;

-- --- PA_QA_DB ---
GRANT SELECT ON ALL TABLES    IN SCHEMA PA_QA_DB.ANALYTICS TO ROLE PA_ANALYST_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PA_QA_DB.ANALYTICS TO ROLE PA_ANALYST_ROLE;
GRANT SELECT ON ALL VIEWS     IN SCHEMA PA_QA_DB.ANALYTICS TO ROLE PA_ANALYST_ROLE;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA PA_QA_DB.ANALYTICS TO ROLE PA_ANALYST_ROLE;

-- --- PA_PROD_DB ---
GRANT SELECT ON ALL TABLES    IN SCHEMA PA_PROD_DB.ANALYTICS TO ROLE PA_ANALYST_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PA_PROD_DB.ANALYTICS TO ROLE PA_ANALYST_ROLE;
GRANT SELECT ON ALL VIEWS     IN SCHEMA PA_PROD_DB.ANALYTICS TO ROLE PA_ANALYST_ROLE;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA PA_PROD_DB.ANALYTICS TO ROLE PA_ANALYST_ROLE;


-- =========================================================================
-- 5c. PA_AI_ENGINEER_ROLE — Cortex AI Grants
-- =========================================================================
-- AI schema: create AI pipeline objects (tables, views, dynamic tables)
-- ANALYTICS: read access for building AI features on Gold-layer data
-- =========================================================================

-- --- PA_DEV_DB ---
GRANT CREATE TABLE        ON SCHEMA PA_DEV_DB.AI TO ROLE PA_AI_ENGINEER_ROLE;
GRANT CREATE VIEW         ON SCHEMA PA_DEV_DB.AI TO ROLE PA_AI_ENGINEER_ROLE;
GRANT CREATE DYNAMIC TABLE ON SCHEMA PA_DEV_DB.AI TO ROLE PA_AI_ENGINEER_ROLE;

GRANT SELECT ON ALL TABLES    IN SCHEMA PA_DEV_DB.AI        TO ROLE PA_AI_ENGINEER_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PA_DEV_DB.AI        TO ROLE PA_AI_ENGINEER_ROLE;
GRANT SELECT ON ALL VIEWS     IN SCHEMA PA_DEV_DB.AI        TO ROLE PA_AI_ENGINEER_ROLE;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA PA_DEV_DB.AI        TO ROLE PA_AI_ENGINEER_ROLE;
GRANT SELECT ON ALL TABLES    IN SCHEMA PA_DEV_DB.ANALYTICS TO ROLE PA_AI_ENGINEER_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PA_DEV_DB.ANALYTICS TO ROLE PA_AI_ENGINEER_ROLE;
GRANT SELECT ON ALL VIEWS     IN SCHEMA PA_DEV_DB.ANALYTICS TO ROLE PA_AI_ENGINEER_ROLE;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA PA_DEV_DB.ANALYTICS TO ROLE PA_AI_ENGINEER_ROLE;

-- --- PA_QA_DB ---
GRANT CREATE TABLE        ON SCHEMA PA_QA_DB.AI TO ROLE PA_AI_ENGINEER_ROLE;
GRANT CREATE VIEW         ON SCHEMA PA_QA_DB.AI TO ROLE PA_AI_ENGINEER_ROLE;
GRANT CREATE DYNAMIC TABLE ON SCHEMA PA_QA_DB.AI TO ROLE PA_AI_ENGINEER_ROLE;

GRANT SELECT ON ALL TABLES    IN SCHEMA PA_QA_DB.AI        TO ROLE PA_AI_ENGINEER_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PA_QA_DB.AI        TO ROLE PA_AI_ENGINEER_ROLE;
GRANT SELECT ON ALL VIEWS     IN SCHEMA PA_QA_DB.AI        TO ROLE PA_AI_ENGINEER_ROLE;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA PA_QA_DB.AI        TO ROLE PA_AI_ENGINEER_ROLE;
GRANT SELECT ON ALL TABLES    IN SCHEMA PA_QA_DB.ANALYTICS TO ROLE PA_AI_ENGINEER_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PA_QA_DB.ANALYTICS TO ROLE PA_AI_ENGINEER_ROLE;
GRANT SELECT ON ALL VIEWS     IN SCHEMA PA_QA_DB.ANALYTICS TO ROLE PA_AI_ENGINEER_ROLE;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA PA_QA_DB.ANALYTICS TO ROLE PA_AI_ENGINEER_ROLE;

-- --- PA_PROD_DB ---
GRANT CREATE TABLE        ON SCHEMA PA_PROD_DB.AI TO ROLE PA_AI_ENGINEER_ROLE;
GRANT CREATE VIEW         ON SCHEMA PA_PROD_DB.AI TO ROLE PA_AI_ENGINEER_ROLE;
GRANT CREATE DYNAMIC TABLE ON SCHEMA PA_PROD_DB.AI TO ROLE PA_AI_ENGINEER_ROLE;

GRANT SELECT ON ALL TABLES    IN SCHEMA PA_PROD_DB.AI        TO ROLE PA_AI_ENGINEER_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PA_PROD_DB.AI        TO ROLE PA_AI_ENGINEER_ROLE;
GRANT SELECT ON ALL VIEWS     IN SCHEMA PA_PROD_DB.AI        TO ROLE PA_AI_ENGINEER_ROLE;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA PA_PROD_DB.AI        TO ROLE PA_AI_ENGINEER_ROLE;
GRANT SELECT ON ALL TABLES    IN SCHEMA PA_PROD_DB.ANALYTICS TO ROLE PA_AI_ENGINEER_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PA_PROD_DB.ANALYTICS TO ROLE PA_AI_ENGINEER_ROLE;
GRANT SELECT ON ALL VIEWS     IN SCHEMA PA_PROD_DB.ANALYTICS TO ROLE PA_AI_ENGINEER_ROLE;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA PA_PROD_DB.ANALYTICS TO ROLE PA_AI_ENGINEER_ROLE;


-- =========================================================================
-- 5d. PA_DATA_STEWARD_ROLE — Governance Grants
-- =========================================================================
-- Account-level: APPLY MASKING POLICY, APPLY ROW ACCESS POLICY, APPLY TAG
-- Schema-level: SELECT on all schemas (must inspect data for classification)
-- No CREATE privileges on data objects — stewards govern, not build
-- =========================================================================

USE ROLE ACCOUNTADMIN;

GRANT APPLY MASKING POLICY    ON ACCOUNT TO ROLE PA_DATA_STEWARD_ROLE;
GRANT APPLY ROW ACCESS POLICY ON ACCOUNT TO ROLE PA_DATA_STEWARD_ROLE;
GRANT APPLY TAG               ON ACCOUNT TO ROLE PA_DATA_STEWARD_ROLE;

USE ROLE SECURITYADMIN;

-- --- PA_DEV_DB ---
GRANT SELECT ON ALL TABLES    IN SCHEMA PA_DEV_DB.RAW       TO ROLE PA_DATA_STEWARD_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PA_DEV_DB.RAW       TO ROLE PA_DATA_STEWARD_ROLE;
GRANT SELECT ON ALL TABLES    IN SCHEMA PA_DEV_DB.CURATED   TO ROLE PA_DATA_STEWARD_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PA_DEV_DB.CURATED   TO ROLE PA_DATA_STEWARD_ROLE;
GRANT SELECT ON ALL TABLES    IN SCHEMA PA_DEV_DB.ANALYTICS TO ROLE PA_DATA_STEWARD_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PA_DEV_DB.ANALYTICS TO ROLE PA_DATA_STEWARD_ROLE;
GRANT SELECT ON ALL TABLES    IN SCHEMA PA_DEV_DB.AI        TO ROLE PA_DATA_STEWARD_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PA_DEV_DB.AI        TO ROLE PA_DATA_STEWARD_ROLE;
GRANT SELECT ON ALL VIEWS     IN SCHEMA PA_DEV_DB.RAW       TO ROLE PA_DATA_STEWARD_ROLE;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA PA_DEV_DB.RAW       TO ROLE PA_DATA_STEWARD_ROLE;
GRANT SELECT ON ALL VIEWS     IN SCHEMA PA_DEV_DB.CURATED   TO ROLE PA_DATA_STEWARD_ROLE;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA PA_DEV_DB.CURATED   TO ROLE PA_DATA_STEWARD_ROLE;
GRANT SELECT ON ALL VIEWS     IN SCHEMA PA_DEV_DB.ANALYTICS TO ROLE PA_DATA_STEWARD_ROLE;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA PA_DEV_DB.ANALYTICS TO ROLE PA_DATA_STEWARD_ROLE;
GRANT SELECT ON ALL VIEWS     IN SCHEMA PA_DEV_DB.AI        TO ROLE PA_DATA_STEWARD_ROLE;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA PA_DEV_DB.AI        TO ROLE PA_DATA_STEWARD_ROLE;

-- --- PA_QA_DB ---
GRANT SELECT ON ALL TABLES    IN SCHEMA PA_QA_DB.RAW       TO ROLE PA_DATA_STEWARD_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PA_QA_DB.RAW       TO ROLE PA_DATA_STEWARD_ROLE;
GRANT SELECT ON ALL TABLES    IN SCHEMA PA_QA_DB.CURATED   TO ROLE PA_DATA_STEWARD_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PA_QA_DB.CURATED   TO ROLE PA_DATA_STEWARD_ROLE;
GRANT SELECT ON ALL TABLES    IN SCHEMA PA_QA_DB.ANALYTICS TO ROLE PA_DATA_STEWARD_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PA_QA_DB.ANALYTICS TO ROLE PA_DATA_STEWARD_ROLE;
GRANT SELECT ON ALL TABLES    IN SCHEMA PA_QA_DB.AI        TO ROLE PA_DATA_STEWARD_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PA_QA_DB.AI        TO ROLE PA_DATA_STEWARD_ROLE;
GRANT SELECT ON ALL VIEWS     IN SCHEMA PA_QA_DB.RAW       TO ROLE PA_DATA_STEWARD_ROLE;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA PA_QA_DB.RAW       TO ROLE PA_DATA_STEWARD_ROLE;
GRANT SELECT ON ALL VIEWS     IN SCHEMA PA_QA_DB.CURATED   TO ROLE PA_DATA_STEWARD_ROLE;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA PA_QA_DB.CURATED   TO ROLE PA_DATA_STEWARD_ROLE;
GRANT SELECT ON ALL VIEWS     IN SCHEMA PA_QA_DB.ANALYTICS TO ROLE PA_DATA_STEWARD_ROLE;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA PA_QA_DB.ANALYTICS TO ROLE PA_DATA_STEWARD_ROLE;
GRANT SELECT ON ALL VIEWS     IN SCHEMA PA_QA_DB.AI        TO ROLE PA_DATA_STEWARD_ROLE;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA PA_QA_DB.AI        TO ROLE PA_DATA_STEWARD_ROLE;

-- --- PA_PROD_DB ---
GRANT SELECT ON ALL TABLES    IN SCHEMA PA_PROD_DB.RAW       TO ROLE PA_DATA_STEWARD_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PA_PROD_DB.RAW       TO ROLE PA_DATA_STEWARD_ROLE;
GRANT SELECT ON ALL TABLES    IN SCHEMA PA_PROD_DB.CURATED   TO ROLE PA_DATA_STEWARD_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PA_PROD_DB.CURATED   TO ROLE PA_DATA_STEWARD_ROLE;
GRANT SELECT ON ALL TABLES    IN SCHEMA PA_PROD_DB.ANALYTICS TO ROLE PA_DATA_STEWARD_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PA_PROD_DB.ANALYTICS TO ROLE PA_DATA_STEWARD_ROLE;
GRANT SELECT ON ALL TABLES    IN SCHEMA PA_PROD_DB.AI        TO ROLE PA_DATA_STEWARD_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PA_PROD_DB.AI        TO ROLE PA_DATA_STEWARD_ROLE;
GRANT SELECT ON ALL VIEWS     IN SCHEMA PA_PROD_DB.RAW       TO ROLE PA_DATA_STEWARD_ROLE;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA PA_PROD_DB.RAW       TO ROLE PA_DATA_STEWARD_ROLE;
GRANT SELECT ON ALL VIEWS     IN SCHEMA PA_PROD_DB.CURATED   TO ROLE PA_DATA_STEWARD_ROLE;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA PA_PROD_DB.CURATED   TO ROLE PA_DATA_STEWARD_ROLE;
GRANT SELECT ON ALL VIEWS     IN SCHEMA PA_PROD_DB.ANALYTICS TO ROLE PA_DATA_STEWARD_ROLE;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA PA_PROD_DB.ANALYTICS TO ROLE PA_DATA_STEWARD_ROLE;
GRANT SELECT ON ALL VIEWS     IN SCHEMA PA_PROD_DB.AI        TO ROLE PA_DATA_STEWARD_ROLE;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA PA_PROD_DB.AI        TO ROLE PA_DATA_STEWARD_ROLE;


-- =========================================================================
-- 5e. PA_CICD_ROLE — Deployment Grants
-- =========================================================================
-- Full CREATE privileges across all schemas in all environments.
-- CI/CD deploys objects under SYSADMIN ownership via CICD_ROLE → SYSADMIN.
-- =========================================================================

USE ROLE SECURITYADMIN;

-- --- PA_DEV_DB ---
GRANT CREATE TABLE          ON SCHEMA PA_DEV_DB.RAW       TO ROLE PA_CICD_ROLE;
GRANT CREATE STAGE          ON SCHEMA PA_DEV_DB.RAW       TO ROLE PA_CICD_ROLE;
GRANT CREATE FILE FORMAT    ON SCHEMA PA_DEV_DB.RAW       TO ROLE PA_CICD_ROLE;
GRANT CREATE PIPE           ON SCHEMA PA_DEV_DB.RAW       TO ROLE PA_CICD_ROLE;
GRANT CREATE STREAM         ON SCHEMA PA_DEV_DB.RAW       TO ROLE PA_CICD_ROLE;
GRANT CREATE TASK           ON SCHEMA PA_DEV_DB.RAW       TO ROLE PA_CICD_ROLE;
GRANT CREATE DYNAMIC TABLE  ON SCHEMA PA_DEV_DB.CURATED   TO ROLE PA_CICD_ROLE;
GRANT CREATE VIEW           ON SCHEMA PA_DEV_DB.CURATED   TO ROLE PA_CICD_ROLE;
GRANT CREATE TABLE          ON SCHEMA PA_DEV_DB.CURATED   TO ROLE PA_CICD_ROLE;
GRANT CREATE STREAM         ON SCHEMA PA_DEV_DB.CURATED   TO ROLE PA_CICD_ROLE;
GRANT CREATE TASK           ON SCHEMA PA_DEV_DB.CURATED   TO ROLE PA_CICD_ROLE;
GRANT CREATE TABLE          ON SCHEMA PA_DEV_DB.ANALYTICS TO ROLE PA_CICD_ROLE;
GRANT CREATE VIEW           ON SCHEMA PA_DEV_DB.ANALYTICS TO ROLE PA_CICD_ROLE;
GRANT CREATE DYNAMIC TABLE  ON SCHEMA PA_DEV_DB.ANALYTICS TO ROLE PA_CICD_ROLE;
GRANT CREATE TABLE          ON SCHEMA PA_DEV_DB.AI        TO ROLE PA_CICD_ROLE;
GRANT CREATE VIEW           ON SCHEMA PA_DEV_DB.AI        TO ROLE PA_CICD_ROLE;
GRANT CREATE DYNAMIC TABLE  ON SCHEMA PA_DEV_DB.AI        TO ROLE PA_CICD_ROLE;

GRANT SELECT ON ALL TABLES    IN SCHEMA PA_DEV_DB.RAW       TO ROLE PA_CICD_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PA_DEV_DB.RAW       TO ROLE PA_CICD_ROLE;
GRANT SELECT ON ALL TABLES    IN SCHEMA PA_DEV_DB.CURATED   TO ROLE PA_CICD_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PA_DEV_DB.CURATED   TO ROLE PA_CICD_ROLE;
GRANT SELECT ON ALL TABLES    IN SCHEMA PA_DEV_DB.ANALYTICS TO ROLE PA_CICD_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PA_DEV_DB.ANALYTICS TO ROLE PA_CICD_ROLE;
GRANT SELECT ON ALL TABLES    IN SCHEMA PA_DEV_DB.AI        TO ROLE PA_CICD_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PA_DEV_DB.AI        TO ROLE PA_CICD_ROLE;
GRANT SELECT ON ALL VIEWS     IN SCHEMA PA_DEV_DB.RAW       TO ROLE PA_CICD_ROLE;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA PA_DEV_DB.RAW       TO ROLE PA_CICD_ROLE;
GRANT SELECT ON ALL VIEWS     IN SCHEMA PA_DEV_DB.CURATED   TO ROLE PA_CICD_ROLE;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA PA_DEV_DB.CURATED   TO ROLE PA_CICD_ROLE;
GRANT SELECT ON ALL VIEWS     IN SCHEMA PA_DEV_DB.ANALYTICS TO ROLE PA_CICD_ROLE;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA PA_DEV_DB.ANALYTICS TO ROLE PA_CICD_ROLE;
GRANT SELECT ON ALL VIEWS     IN SCHEMA PA_DEV_DB.AI        TO ROLE PA_CICD_ROLE;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA PA_DEV_DB.AI        TO ROLE PA_CICD_ROLE;

-- --- PA_QA_DB ---
GRANT CREATE TABLE          ON SCHEMA PA_QA_DB.RAW       TO ROLE PA_CICD_ROLE;
GRANT CREATE STAGE          ON SCHEMA PA_QA_DB.RAW       TO ROLE PA_CICD_ROLE;
GRANT CREATE FILE FORMAT    ON SCHEMA PA_QA_DB.RAW       TO ROLE PA_CICD_ROLE;
GRANT CREATE PIPE           ON SCHEMA PA_QA_DB.RAW       TO ROLE PA_CICD_ROLE;
GRANT CREATE STREAM         ON SCHEMA PA_QA_DB.RAW       TO ROLE PA_CICD_ROLE;
GRANT CREATE TASK           ON SCHEMA PA_QA_DB.RAW       TO ROLE PA_CICD_ROLE;
GRANT CREATE DYNAMIC TABLE  ON SCHEMA PA_QA_DB.CURATED   TO ROLE PA_CICD_ROLE;
GRANT CREATE VIEW           ON SCHEMA PA_QA_DB.CURATED   TO ROLE PA_CICD_ROLE;
GRANT CREATE TABLE          ON SCHEMA PA_QA_DB.CURATED   TO ROLE PA_CICD_ROLE;
GRANT CREATE STREAM         ON SCHEMA PA_QA_DB.CURATED   TO ROLE PA_CICD_ROLE;
GRANT CREATE TASK           ON SCHEMA PA_QA_DB.CURATED   TO ROLE PA_CICD_ROLE;
GRANT CREATE TABLE          ON SCHEMA PA_QA_DB.ANALYTICS TO ROLE PA_CICD_ROLE;
GRANT CREATE VIEW           ON SCHEMA PA_QA_DB.ANALYTICS TO ROLE PA_CICD_ROLE;
GRANT CREATE DYNAMIC TABLE  ON SCHEMA PA_QA_DB.ANALYTICS TO ROLE PA_CICD_ROLE;
GRANT CREATE TABLE          ON SCHEMA PA_QA_DB.AI        TO ROLE PA_CICD_ROLE;
GRANT CREATE VIEW           ON SCHEMA PA_QA_DB.AI        TO ROLE PA_CICD_ROLE;
GRANT CREATE DYNAMIC TABLE  ON SCHEMA PA_QA_DB.AI        TO ROLE PA_CICD_ROLE;

GRANT SELECT ON ALL TABLES    IN SCHEMA PA_QA_DB.RAW       TO ROLE PA_CICD_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PA_QA_DB.RAW       TO ROLE PA_CICD_ROLE;
GRANT SELECT ON ALL TABLES    IN SCHEMA PA_QA_DB.CURATED   TO ROLE PA_CICD_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PA_QA_DB.CURATED   TO ROLE PA_CICD_ROLE;
GRANT SELECT ON ALL TABLES    IN SCHEMA PA_QA_DB.ANALYTICS TO ROLE PA_CICD_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PA_QA_DB.ANALYTICS TO ROLE PA_CICD_ROLE;
GRANT SELECT ON ALL TABLES    IN SCHEMA PA_QA_DB.AI        TO ROLE PA_CICD_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PA_QA_DB.AI        TO ROLE PA_CICD_ROLE;
GRANT SELECT ON ALL VIEWS     IN SCHEMA PA_QA_DB.RAW       TO ROLE PA_CICD_ROLE;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA PA_QA_DB.RAW       TO ROLE PA_CICD_ROLE;
GRANT SELECT ON ALL VIEWS     IN SCHEMA PA_QA_DB.CURATED   TO ROLE PA_CICD_ROLE;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA PA_QA_DB.CURATED   TO ROLE PA_CICD_ROLE;
GRANT SELECT ON ALL VIEWS     IN SCHEMA PA_QA_DB.ANALYTICS TO ROLE PA_CICD_ROLE;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA PA_QA_DB.ANALYTICS TO ROLE PA_CICD_ROLE;
GRANT SELECT ON ALL VIEWS     IN SCHEMA PA_QA_DB.AI        TO ROLE PA_CICD_ROLE;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA PA_QA_DB.AI        TO ROLE PA_CICD_ROLE;

-- --- PA_PROD_DB ---
GRANT CREATE TABLE          ON SCHEMA PA_PROD_DB.RAW       TO ROLE PA_CICD_ROLE;
GRANT CREATE STAGE          ON SCHEMA PA_PROD_DB.RAW       TO ROLE PA_CICD_ROLE;
GRANT CREATE FILE FORMAT    ON SCHEMA PA_PROD_DB.RAW       TO ROLE PA_CICD_ROLE;
GRANT CREATE PIPE           ON SCHEMA PA_PROD_DB.RAW       TO ROLE PA_CICD_ROLE;
GRANT CREATE STREAM         ON SCHEMA PA_PROD_DB.RAW       TO ROLE PA_CICD_ROLE;
GRANT CREATE TASK           ON SCHEMA PA_PROD_DB.RAW       TO ROLE PA_CICD_ROLE;
GRANT CREATE DYNAMIC TABLE  ON SCHEMA PA_PROD_DB.CURATED   TO ROLE PA_CICD_ROLE;
GRANT CREATE VIEW           ON SCHEMA PA_PROD_DB.CURATED   TO ROLE PA_CICD_ROLE;
GRANT CREATE TABLE          ON SCHEMA PA_PROD_DB.CURATED   TO ROLE PA_CICD_ROLE;
GRANT CREATE STREAM         ON SCHEMA PA_PROD_DB.CURATED   TO ROLE PA_CICD_ROLE;
GRANT CREATE TASK           ON SCHEMA PA_PROD_DB.CURATED   TO ROLE PA_CICD_ROLE;
GRANT CREATE TABLE          ON SCHEMA PA_PROD_DB.ANALYTICS TO ROLE PA_CICD_ROLE;
GRANT CREATE VIEW           ON SCHEMA PA_PROD_DB.ANALYTICS TO ROLE PA_CICD_ROLE;
GRANT CREATE DYNAMIC TABLE  ON SCHEMA PA_PROD_DB.ANALYTICS TO ROLE PA_CICD_ROLE;
GRANT CREATE TABLE          ON SCHEMA PA_PROD_DB.AI        TO ROLE PA_CICD_ROLE;
GRANT CREATE VIEW           ON SCHEMA PA_PROD_DB.AI        TO ROLE PA_CICD_ROLE;
GRANT CREATE DYNAMIC TABLE  ON SCHEMA PA_PROD_DB.AI        TO ROLE PA_CICD_ROLE;

GRANT SELECT ON ALL TABLES    IN SCHEMA PA_PROD_DB.RAW       TO ROLE PA_CICD_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PA_PROD_DB.RAW       TO ROLE PA_CICD_ROLE;
GRANT SELECT ON ALL TABLES    IN SCHEMA PA_PROD_DB.CURATED   TO ROLE PA_CICD_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PA_PROD_DB.CURATED   TO ROLE PA_CICD_ROLE;
GRANT SELECT ON ALL TABLES    IN SCHEMA PA_PROD_DB.ANALYTICS TO ROLE PA_CICD_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PA_PROD_DB.ANALYTICS TO ROLE PA_CICD_ROLE;
GRANT SELECT ON ALL TABLES    IN SCHEMA PA_PROD_DB.AI        TO ROLE PA_CICD_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PA_PROD_DB.AI        TO ROLE PA_CICD_ROLE;
GRANT SELECT ON ALL VIEWS     IN SCHEMA PA_PROD_DB.RAW       TO ROLE PA_CICD_ROLE;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA PA_PROD_DB.RAW       TO ROLE PA_CICD_ROLE;
GRANT SELECT ON ALL VIEWS     IN SCHEMA PA_PROD_DB.CURATED   TO ROLE PA_CICD_ROLE;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA PA_PROD_DB.CURATED   TO ROLE PA_CICD_ROLE;
GRANT SELECT ON ALL VIEWS     IN SCHEMA PA_PROD_DB.ANALYTICS TO ROLE PA_CICD_ROLE;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA PA_PROD_DB.ANALYTICS TO ROLE PA_CICD_ROLE;
GRANT SELECT ON ALL VIEWS     IN SCHEMA PA_PROD_DB.AI        TO ROLE PA_CICD_ROLE;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA PA_PROD_DB.AI        TO ROLE PA_CICD_ROLE;


-- =========================================================================
-- 5f. PA_PHI_ACCESS_ROLE — Break-Glass PHI Access
-- =========================================================================
-- Isolated role — SELECT on ANALYTICS and AI schemas only.
-- Masking policy exemption is configured in Phase 9.
-- This role is NOT inherited by any other role (except SYSADMIN).
-- =========================================================================

-- --- PA_DEV_DB ---
GRANT SELECT ON ALL TABLES    IN SCHEMA PA_DEV_DB.ANALYTICS TO ROLE PA_PHI_ACCESS_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PA_DEV_DB.ANALYTICS TO ROLE PA_PHI_ACCESS_ROLE;
GRANT SELECT ON ALL VIEWS     IN SCHEMA PA_DEV_DB.ANALYTICS TO ROLE PA_PHI_ACCESS_ROLE;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA PA_DEV_DB.ANALYTICS TO ROLE PA_PHI_ACCESS_ROLE;
GRANT SELECT ON ALL TABLES    IN SCHEMA PA_DEV_DB.AI        TO ROLE PA_PHI_ACCESS_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PA_DEV_DB.AI        TO ROLE PA_PHI_ACCESS_ROLE;
GRANT SELECT ON ALL VIEWS     IN SCHEMA PA_DEV_DB.AI        TO ROLE PA_PHI_ACCESS_ROLE;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA PA_DEV_DB.AI        TO ROLE PA_PHI_ACCESS_ROLE;

-- --- PA_QA_DB ---
GRANT SELECT ON ALL TABLES    IN SCHEMA PA_QA_DB.ANALYTICS TO ROLE PA_PHI_ACCESS_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PA_QA_DB.ANALYTICS TO ROLE PA_PHI_ACCESS_ROLE;
GRANT SELECT ON ALL VIEWS     IN SCHEMA PA_QA_DB.ANALYTICS TO ROLE PA_PHI_ACCESS_ROLE;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA PA_QA_DB.ANALYTICS TO ROLE PA_PHI_ACCESS_ROLE;
GRANT SELECT ON ALL TABLES    IN SCHEMA PA_QA_DB.AI        TO ROLE PA_PHI_ACCESS_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PA_QA_DB.AI        TO ROLE PA_PHI_ACCESS_ROLE;
GRANT SELECT ON ALL VIEWS     IN SCHEMA PA_QA_DB.AI        TO ROLE PA_PHI_ACCESS_ROLE;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA PA_QA_DB.AI        TO ROLE PA_PHI_ACCESS_ROLE;

-- --- PA_PROD_DB ---
GRANT SELECT ON ALL TABLES    IN SCHEMA PA_PROD_DB.ANALYTICS TO ROLE PA_PHI_ACCESS_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PA_PROD_DB.ANALYTICS TO ROLE PA_PHI_ACCESS_ROLE;
GRANT SELECT ON ALL VIEWS     IN SCHEMA PA_PROD_DB.ANALYTICS TO ROLE PA_PHI_ACCESS_ROLE;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA PA_PROD_DB.ANALYTICS TO ROLE PA_PHI_ACCESS_ROLE;
GRANT SELECT ON ALL TABLES    IN SCHEMA PA_PROD_DB.AI        TO ROLE PA_PHI_ACCESS_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PA_PROD_DB.AI        TO ROLE PA_PHI_ACCESS_ROLE;
GRANT SELECT ON ALL VIEWS     IN SCHEMA PA_PROD_DB.AI        TO ROLE PA_PHI_ACCESS_ROLE;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA PA_PROD_DB.AI        TO ROLE PA_PHI_ACCESS_ROLE;


-- =============================================================================
-- SECTION 6: PA_AUDIT_ROLE — Placeholder
-- =============================================================================
-- The audit database (PA_AUDIT_DB or equivalent) does not exist yet.
-- It is created in Phase 11. Grants for PA_AUDIT_ROLE on the audit DB
-- will be added in that phase.
--
-- For now, the role exists in the hierarchy with PA_QUERY_WH access only.
-- No data grants until the audit database is created.
-- =============================================================================


-- =============================================================================
-- SECTION 7: User Assignment Scaffold (COMMENTED)
-- =============================================================================
-- Uncomment and populate when users are onboarded. Replace << USERNAME >>
-- with actual Snowflake user names.
--
-- USE ROLE SECURITYADMIN;
--
-- -- Human users
-- GRANT ROLE PA_DATA_ENGINEER_ROLE TO USER << DATA_ENGINEER_USERNAME >>;
-- GRANT ROLE PA_ANALYST_ROLE       TO USER << ANALYST_USERNAME >>;
-- GRANT ROLE PA_AI_ENGINEER_ROLE   TO USER << AI_ENGINEER_USERNAME >>;
-- GRANT ROLE PA_DATA_STEWARD_ROLE  TO USER << DATA_STEWARD_USERNAME >>;
-- GRANT ROLE PA_AUDIT_ROLE         TO USER << AUDITOR_USERNAME >>;
--
-- -- PHI break-glass (tightly controlled — document each assignment)
-- GRANT ROLE PA_PHI_ACCESS_ROLE    TO USER << PHI_AUTHORIZED_USERNAME >>;
--
-- -- CI/CD service account
-- -- CREATE USER IF NOT EXISTS PA_CICD_SVC_ACCOUNT
-- --   LOGIN_NAME     = 'PA_CICD_SVC_ACCOUNT'
-- --   DISPLAY_NAME   = 'PriorAuthIQ CI/CD Service Account'
-- --   DEFAULT_ROLE   = 'PA_CICD_ROLE'
-- --   MUST_CHANGE_PASSWORD = FALSE
-- --   RSA_PUBLIC_KEY = '<< PLACEHOLDER: Base64-encoded RSA public key >>'
-- --   COMMENT        = 'GitHub Actions service account — key-pair auth only';
-- --
-- -- GRANT ROLE PA_CICD_ROLE TO USER PA_CICD_SVC_ACCOUNT;
-- =============================================================================


-- =============================================================================
-- EXIT CRITERIA — Verification Queries
-- =============================================================================
-- Run these after deployment to confirm Phase 3 is complete.
--
-- -- 1. Confirm all 7 custom roles exist
-- SHOW ROLES LIKE 'PA_%';
--
-- -- 2. Verify role hierarchy — each role's parent grants
-- SHOW GRANTS OF ROLE PA_ANALYST_ROLE;
-- -- Expected: granted to PA_DATA_ENGINEER_ROLE, PA_AI_ENGINEER_ROLE
--
-- SHOW GRANTS OF ROLE PA_DATA_ENGINEER_ROLE;
-- -- Expected: granted to SYSADMIN
--
-- SHOW GRANTS OF ROLE PA_AI_ENGINEER_ROLE;
-- -- Expected: granted to SYSADMIN
--
-- SHOW GRANTS OF ROLE PA_CICD_ROLE;
-- -- Expected: granted to SYSADMIN
--
-- SHOW GRANTS OF ROLE PA_AUDIT_ROLE;
-- -- Expected: granted to SYSADMIN
--
-- SHOW GRANTS OF ROLE PA_PHI_ACCESS_ROLE;
-- -- Expected: granted to SYSADMIN only (isolated)
--
-- SHOW GRANTS OF ROLE PA_DATA_STEWARD_ROLE;
-- -- Expected: granted to SECURITYADMIN
--
-- -- 3. Verify warehouse USAGE grants
-- SHOW GRANTS ON WAREHOUSE PA_INGESTION_WH;
-- SHOW GRANTS ON WAREHOUSE PA_TRANSFORM_WH;
-- SHOW GRANTS ON WAREHOUSE PA_QUERY_WH;
-- SHOW GRANTS ON WAREHOUSE PA_AI_CORTEX_WH;
-- SHOW GRANTS ON WAREHOUSE PA_ADMIN_WH;
-- SHOW GRANTS ON WAREHOUSE PA_CICD_WH;
--
-- -- 4. Spot-check: PA_ANALYST_ROLE should only see ANALYTICS + PA_QUERY_WH
-- SHOW GRANTS TO ROLE PA_ANALYST_ROLE;
--
-- -- 5. Spot-check: PA_AI_ENGINEER_ROLE should see AI + ANALYTICS + PA_AI_CORTEX_WH
-- SHOW GRANTS TO ROLE PA_AI_ENGINEER_ROLE;
--
-- -- 6. Confirm NO GRANT OWNERSHIP to any functional role
-- -- (Manually inspect outputs of steps 3-5 for any OWNERSHIP grants)
--
-- -- 7. Confirm account-level governance grants for Data Steward
-- SHOW GRANTS TO ROLE PA_DATA_STEWARD_ROLE;
-- -- Expected: APPLY MASKING POLICY, APPLY ROW ACCESS POLICY, APPLY TAG on ACCOUNT
-- =============================================================================
-- END OF PHASE 3
-- =============================================================================
